/*
	This file is generated by net_compiler.py.
	The use of included functions list as follows:

	Input:
	Input(int dim1,int dim2,int dim3,int dim4,char *top,char *name)

	Convolution:
	Convolution(int num_input,int num_output,int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,int group,int dilation,int axis,bool bias_term,bool force_nd_im2col,char *bottom,char *top, char *name,int is_merge_relu,struct handler *hd)

	BatchNorm:
	inferx_batchnorm(float moving_average_fraction,float eps,bool use_global_stats,char *bottom,char *top,char *name,struct handler *hd)

	Scale:
	inferx_scale(int axis,int num_axes,bool bias_term,char *bottom,char *top,char *name,struct handler *hd)

	ReLU:
	ReLU(char *bottom,char *top,char *name,struct handler *hd)

	Pooling:
	inferx_pooling(int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,enum PoolMethod pool,char *bottom,char *top,char *name,struct handler *hd)

	Reshape:
	inferx_reshape(int batch_size, int channels, int height, int weidth char *bottom, char *top char *name,struct handler *hd)

	Concat:
	inferx_concat(int num_output,int axis,int concat_dim,int bottom_num,char **bottoms,char *top,char *name,struct handler *hd)

	Region:
	Region(int number, int classes, int coords, char * bottom, char *top, char *name,struct handler *hd)
*/

#include "inferxlite_common.h"
#include "interface.h"
void JDminiYOLOv2(char * path, char * model, char * data,void *pdata, void **pout,struct handler *hd)
{
        printf("=== enter YOLOtiny ===\n");
	char* bottom_vector[2];

	static long nchw[4];
	inferx_net_preprocess(data,model,nchw,hd);

	inferx_input(nchw,pdata,"data_data","data",model,data,hd);

	inferx_convolution(3,16,3,3,1,1,1,1,1,1,1,false,false,"data_data","layer1-conv_data","layer1-conv",model,data, 0,hd);


    //*
    if (pout)
{
        *pout = inferx_get_data("layer1-conv_data",data,hd);
printf("aaa %x\n", *pout);
}




	inferx_batchnorm(0.999,1e-5,true,"layer1-conv_data","layer1-conv_data","layer1-bn",model,data,hd);

	inferx_scale(1,1,true,"layer1-conv_data","layer1-conv_data","layer1-scale",model,data,hd);
	inferx_relu("layer1-conv_data","layer1-conv_data","layer1-act",model,data,hd);


	inferx_pooling(2,2,2,2,0,0,MAX,"layer1-conv_data","layer2-maxpool_data","layer2-maxpool",model,data,hd);
	inferx_convolution(16,32,3,3,1,1,1,1,1,1,1,false,false,"layer2-maxpool_data","layer3-conv_data","layer3-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer3-conv_data","layer3-conv_data","layer3-bn",model,data,hd);
	inferx_scale(1,1,true,"layer3-conv_data","layer3-conv_data","layer3-scale",model,data,hd);
	inferx_relu("layer3-conv_data","layer3-conv_data","layer3-act",model,data,hd);
	inferx_pooling(2,2,2,2,0,0,MAX,"layer3-conv_data","layer4-maxpool_data","layer4-maxpool",model,data,hd);
	inferx_convolution(32,64,3,3,1,1,1,1,1,1,1,false,false,"layer4-maxpool_data","layer5-conv_data","layer5-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer5-conv_data","layer5-conv_data","layer5-bn",model,data,hd);
	inferx_scale(1,1,true,"layer5-conv_data","layer5-conv_data","layer5-scale",model,data,hd);
	inferx_relu("layer5-conv_data","layer5-conv_data","layer5-act",model,data,hd);
	inferx_pooling(2,2,2,2,0,0,MAX,"layer5-conv_data","layer6-maxpool_data","layer6-maxpool",model,data,hd);
	inferx_convolution(64,128,3,3,1,1,1,1,1,1,1,false,false,"layer6-maxpool_data","layer7-conv_data","layer7-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer7-conv_data","layer7-conv_data","layer7-bn",model,data,hd);
	inferx_scale(1,1,true,"layer7-conv_data","layer7-conv_data","layer7-scale",model,data,hd);
	inferx_relu("layer7-conv_data","layer7-conv_data","layer7-act",model,data,hd);
	inferx_pooling(2,2,2,2,0,0,MAX,"layer7-conv_data","layer8-maxpool_data","layer8-maxpool",model,data,hd);
	inferx_convolution(128,256,3,3,1,1,1,1,1,1,1,false,false,"layer8-maxpool_data","layer9-conv_data","layer9-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer9-conv_data","layer9-conv_data","layer9-bn",model,data,hd);
	inferx_scale(1,1,true,"layer9-conv_data","layer9-conv_data","layer9-scale",model,data,hd);
	inferx_relu("layer9-conv_data","layer9-conv_data","layer9-act",model,data,hd);
	inferx_pooling(2,2,2,2,0,0,MAX,"layer9-conv_data","layer10-maxpool_data","layer10-maxpool",model,data,hd);
	inferx_convolution(256,512,3,3,1,1,1,1,1,1,1,false,false,"layer10-maxpool_data","layer11-conv_data","layer11-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer11-conv_data","layer11-conv_data","layer11-bn",model,data,hd);
	inferx_scale(1,1,true,"layer11-conv_data","layer11-conv_data","layer11-scale",model,data,hd);
	inferx_relu("layer11-conv_data","layer11-conv_data","layer11-act",model,data,hd);
	inferx_pooling_yolo(2,2,1,1,1,1,MAX,"layer11-conv_data","layer12-maxpool_data","layer12-maxpool",model,data,hd);
	inferx_convolution(512,1024,3,3,1,1,1,1,1,1,1,false,false,"layer12-maxpool_data","layer13-conv_data","layer13-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer13-conv_data","layer13-conv_data","layer13-bn",model,data,hd);
	inferx_scale(1,1,true,"layer13-conv_data","layer13-conv_data","layer13-scale",model,data,hd);
	inferx_relu("layer13-conv_data","layer13-conv_data","layer13-act",model,data,hd);
	inferx_convolution(256,64,1,1,1,1,0,0,1,1,1,false,false,"layer9-conv_data","layer15-conv_data","layer15-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer15-conv_data","layer15-conv_data","layer15-bn",model,data,hd);
	inferx_scale(1,1,true,"layer15-conv_data","layer15-conv_data","layer15-scale",model,data,hd);
	inferx_relu("layer15-conv_data","layer15-conv_data","layer15-act",model,data,hd);
	inferx_reorg(1,256,13,13,"layer15-conv_data","layer16-reorg_data","layer16-reorg",model,data,hd);
	bottom_vector[0] = "layer16-reorg_data";	bottom_vector[1] = "layer13-conv_data";
	inferx_concat(1280,1,1,2,bottom_vector,"layer17-concat_data","layer17-concat",model,data,hd);
	inferx_convolution(1280,1024,3,3,1,1,1,1,1,1,1,false,false,"layer17-concat_data","layer18-conv_data","layer18-conv",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-5,true,"layer18-conv_data","layer18-conv_data","layer18-bn",model,data,hd);
	inferx_scale(1,1,true,"layer18-conv_data","layer18-conv_data","layer18-scale",model,data,hd);
	inferx_relu("layer18-conv_data","layer18-conv_data","layer18-act",model,data,hd);
	inferx_convolution(1024,30,1,1,1,1,0,0,1,1,1,true,false,"layer18-conv_data","layer19-conv_data","layer19-conv",model,data, 0,hd);

	//inferx_region(5,1,4,"layer19-conv_data","layer20-region_data","layer20-region",model,data,hd);

	inferx_finalize("JDminiYOLOv2", hd);return;
}
