/*
	This file is generated by net_compiler.py.
	The use of included functions list as follows:

	Input:
	Input(int dim1,int dim2,int dim3,int dim4,char *top,char *name)

	Convolution:
	Convolution(int num_input,int num_output,int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,int group,int dilation,int axis,bool bias_term,bool force_nd_im2col,char *bottom,char *top, char *name,int is_merge_relu,struct handler *hd)

	BatchNorm:
	inferx_batchnorm(float moving_average_fraction,float eps,bool use_global_stats,char *bottom,char *top,char *name,struct handler *hd)

	Scale:
	inferx_scale(int axis,int num_axes,bool bias_term,char *bottom,char *top,char *name,struct handler *hd)

	ReLU:
	ReLU(char *bottom,char *top,char *name,struct handler *hd)

	Pooling:
	inferx_pooling(int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,enum PoolMethod pool,char *bottom,char *top,char *name,struct handler *hd)

	Eltwise:
	inferx_eltwise(int coeffs_num, float* coeffs,enum EltwiseOp operation,bool stabel_prod_grad,int bottom_num,char **bottoms,char *top, char *name,struct handler *hd)

	Concat:
	inferx_concat(int num_output,int axis,int concat_dim,int bottom_num,char **bottoms,char *top,char *name,struct handler *hd)
*/

#include "inferxlite_common.h"
#include "interface.h"
void ShipSSD(char* path, char* model, char* data, void* pdata, void** pout, struct handler *hd)
{
	float coeffs[2];
	char* bottom_vector[3];

	static int nchw[4];
	inferx_net_preprocess(data,model,nchw,hd);

	inferx_input(nchw,pdata,"data_data","data",model,data,hd);

	inferx_convolution(3,64,7,7,2,2,3,3,1,1,1,true,false,"data_data","conv1_data","conv1",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv1_data","conv1_data","conv1_bn",model,data,hd);
	inferx_scale(1,1,true,"conv1_data","conv1_data","conv1_scale",model,data,hd);
	inferx_relu("conv1_data","conv1_data","conv1_relu",model,data,hd);
	inferx_pooling(2,2,2,2,0,0,MAX,"conv1_data","pool1_data","pool1",model,data,hd);

	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"pool1_data","conv2a_branch2a_data","conv2a_branch2a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv2a_branch2a_data","conv2a_branch2a_data","conv2a_branch2a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv2a_branch2a_data","conv2a_branch2a_data","conv2a_branch2a_scale",model,data,hd);
	inferx_relu("conv2a_branch2a_data","conv2a_branch2a_data","conv2a_branch2a_relu",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"conv2a_branch2a_data","conv2a_branch2b_data","conv2a_branch2b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv2a_branch2b_data","conv2a_branch2b_data","conv2a_branch2b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv2a_branch2b_data","conv2a_branch2b_data","conv2a_branch2b_scale",model,data,hd);
	inferx_relu("conv2a_branch2b_data","conv2a_branch2b_data","conv2a_branch2b_relu",model,data,hd);
	bottom_vector[0] = "pool1_data";	bottom_vector[1] = "conv2a_branch2b_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv2a_data","conv2a",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"conv2a_data","conv2b_branch2a_data","conv2b_branch2a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv2b_branch2a_data","conv2b_branch2a_data","conv2b_branch2a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv2b_branch2a_data","conv2b_branch2a_data","conv2b_branch2a_scale",model,data,hd);
	inferx_relu("conv2b_branch2a_data","conv2b_branch2a_data","conv2b_branch2a_relu",model,data,hd);
	inferx_convolution(64,64,3,3,1,1,1,1,1,1,1,true,false,"conv2b_branch2a_data","conv2b_branch2b_data","conv2b_branch2b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv2b_branch2b_data","conv2b_branch2b_data","conv2b_branch2b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv2b_branch2b_data","conv2b_branch2b_data","conv2b_branch2b_scale",model,data,hd);
	inferx_relu("conv2b_branch2b_data","conv2b_branch2b_data","conv2b_branch2b_relu",model,data,hd);
	bottom_vector[0] = "conv2a_data";	bottom_vector[1] = "conv2b_branch2b_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv2b_data","conv2b",model,data,hd);
	inferx_convolution(64,128,1,1,2,2,0,0,1,1,1,true,false,"conv2b_data","conv3a_branch1_data","conv3a_branch1",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3a_branch1_data","conv3a_branch1_data","conv3a_branch1_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3a_branch1_data","conv3a_branch1_data","conv3a_branch1_scale",model,data,hd);
	inferx_relu("conv3a_branch1_data","conv3a_branch1_data","conv3a_branch1_relu",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"conv3a_branch1_data","conv3a_branch2a_data","conv3a_branch2a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3a_branch2a_data","conv3a_branch2a_data","conv3a_branch2a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3a_branch2a_data","conv3a_branch2a_data","conv3a_branch2a_scale",model,data,hd);
	inferx_relu("conv3a_branch2a_data","conv3a_branch2a_data","conv3a_branch2a_relu",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"conv3a_branch2a_data","conv3a_branch2b_data","conv3a_branch2b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3a_branch2b_data","conv3a_branch2b_data","conv3a_branch2b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3a_branch2b_data","conv3a_branch2b_data","conv3a_branch2b_scale",model,data,hd);
	inferx_relu("conv3a_branch2b_data","conv3a_branch2b_data","conv3a_branch2b_relu",model,data,hd);
	bottom_vector[0] = "conv3a_branch1_data";	bottom_vector[1] = "conv3a_branch2b_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv3a_data","conv3a",model,data,hd);
	inferx_convolution(128,128,1,1,1,1,0,0,1,1,1,true,false,"conv3a_data","conv3b_1x1_data","conv3b_1x1",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3b_1x1_data","conv3b_1x1_data","conv3b_1x1_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3b_1x1_data","conv3b_1x1_data","conv3b_1x1_scale",model,data,hd);
	inferx_relu("conv3b_1x1_data","conv3b_1x1_data","conv3b_1x1_relu",model,data,hd);
	inferx_convolution(128,64,3,3,1,1,1,1,1,1,1,true,false,"conv3b_1x1_data","conv3b_3x3_reduce_data","conv3b_3x3_reduce",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3b_3x3_reduce_data","conv3b_3x3_reduce_data","conv3b_3x3_reduce_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3b_3x3_reduce_data","conv3b_3x3_reduce_data","conv3b_3x3_reduce_scale",model,data,hd);
	inferx_relu("conv3b_3x3_reduce_data","conv3b_3x3_reduce_data","conv3b_3x3_reduce_relu",model,data,hd);
	inferx_convolution(64,128,3,3,1,1,1,1,1,1,1,true,false,"conv3b_3x3_reduce_data","conv3b_3x3_a_data","conv3b_3x3_a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3b_3x3_a_data","conv3b_3x3_a_data","conv3b_3x3_a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3b_3x3_a_data","conv3b_3x3_a_data","conv3b_3x3_a_scale",model,data,hd);
	inferx_relu("conv3b_3x3_a_data","conv3b_3x3_a_data","conv3b_3x3_a_relu",model,data,hd);
	inferx_convolution(128,128,3,3,1,1,1,1,1,1,1,true,false,"conv3b_1x1_data","conv3b_3x3_b_data","conv3b_3x3_b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3b_3x3_b_data","conv3b_3x3_b_data","conv3b_3x3_b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3b_3x3_b_data","conv3b_3x3_b_data","conv3b_3x3_b_scale",model,data,hd);
	inferx_relu("conv3b_3x3_b_data","conv3b_3x3_b_data","conv3b_3x3_b_relu",model,data,hd);
	bottom_vector[0] = "conv3b_1x1_data";	bottom_vector[1] = "conv3b_3x3_a_data";	bottom_vector[2] = "conv3b_3x3_b_data";
	inferx_concat(384,1,1,3,bottom_vector,"conv3b_concat_data","conv3b_concat",model,data,hd);
	inferx_convolution(384,128,3,3,1,1,1,1,1,1,1,true,false,"conv3b_concat_data","conv3b_reduce_data","conv3b_reduce",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv3b_reduce_data","conv3b_reduce_data","conv3b_reduce_bn",model,data,hd);
	inferx_scale(1,1,true,"conv3b_reduce_data","conv3b_reduce_data","conv3b_reduce_scale",model,data,hd);
	inferx_relu("conv3b_reduce_data","conv3b_reduce_data","conv3b_reduce_relu",model,data,hd);
	bottom_vector[0] = "conv3a_data";	bottom_vector[1] = "conv3b_reduce_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv3b_data","conv3b",model,data,hd);
	inferx_convolution(128,256,1,1,2,2,0,0,1,1,1,true,false,"conv3b_data","conv4a_branch1_data","conv4a_branch1",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4a_branch1_data","conv4a_branch1_data","conv4a_branch1_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4a_branch1_data","conv4a_branch1_data","conv4a_branch1_scale",model,data,hd);
	inferx_relu("conv4a_branch1_data","conv4a_branch1_data","conv4a_branch1_relu",model,data,hd);
	inferx_convolution(256,256,3,3,1,1,1,1,1,1,1,true,false,"conv4a_branch1_data","conv4a_branch2a_data","conv4a_branch2a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4a_branch2a_data","conv4a_branch2a_data","conv4a_branch2a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4a_branch2a_data","conv4a_branch2a_data","conv4a_branch2a_scale",model,data,hd);
	inferx_relu("conv4a_branch2a_data","conv4a_branch2a_data","conv4a_branch2a_relu",model,data,hd);
	inferx_convolution(256,256,3,3,1,1,1,1,1,1,1,true,false,"conv4a_branch2a_data","conv4a_branch2b_data","conv4a_branch2b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4a_branch2b_data","conv4a_branch2b_data","conv4a_branch2b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4a_branch2b_data","conv4a_branch2b_data","conv4a_branch2b_scale",model,data,hd);
	inferx_relu("conv4a_branch2b_data","conv4a_branch2b_data","conv4a_branch2b_relu",model,data,hd);
	bottom_vector[0] = "conv4a_branch1_data";	bottom_vector[1] = "conv4a_branch2b_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv4a_data","conv4a",model,data,hd);
	inferx_convolution(256,256,1,1,1,1,0,0,1,1,1,true,false,"conv4a_data","conv4b_1x1_data","conv4b_1x1",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4b_1x1_data","conv4b_1x1_data","conv4b_1x1_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4b_1x1_data","conv4b_1x1_data","conv4b_1x1_scale",model,data,hd);
	inferx_relu("conv4b_1x1_data","conv4b_1x1_data","conv4b_1x1_relu",model,data,hd);
	inferx_convolution(256,128,3,3,1,1,1,1,1,1,1,true,false,"conv4b_1x1_data","conv4b_3x3_reduce_data","conv4b_3x3_reduce",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4b_3x3_reduce_data","conv4b_3x3_reduce_data","conv4b_3x3_reduce_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4b_3x3_reduce_data","conv4b_3x3_reduce_data","conv4b_3x3_reduce_scale",model,data,hd);
	inferx_relu("conv4b_3x3_reduce_data","conv4b_3x3_reduce_data","conv4b_3x3_reduce_relu",model,data,hd);
	inferx_convolution(128,256,3,3,1,1,1,1,1,1,1,true,false,"conv4b_3x3_reduce_data","conv4b_3x3_a_data","conv4b_3x3_a",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4b_3x3_a_data","conv4b_3x3_a_data","conv4b_3x3_a_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4b_3x3_a_data","conv4b_3x3_a_data","conv4b_3x3_a_scale",model,data,hd);
	inferx_relu("conv4b_3x3_a_data","conv4b_3x3_a_data","conv4b_3x3_a_relu",model,data,hd);
	inferx_convolution(256,256,3,3,1,1,1,1,1,1,1,true,false,"conv4b_1x1_data","conv4b_3x3_b_data","conv4b_3x3_b",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4b_3x3_b_data","conv4b_3x3_b_data","conv4b_3x3_b_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4b_3x3_b_data","conv4b_3x3_b_data","conv4b_3x3_b_scale",model,data,hd);
	inferx_relu("conv4b_3x3_b_data","conv4b_3x3_b_data","conv4b_3x3_b_relu",model,data,hd);
	bottom_vector[0] = "conv4b_1x1_data";	bottom_vector[1] = "conv4b_3x3_a_data";	bottom_vector[2] = "conv4b_3x3_b_data";
	inferx_concat(768,1,1,3,bottom_vector,"conv4b_concat_data","conv4b_concat",model,data,hd);
	inferx_convolution(768,256,3,3,1,1,1,1,1,1,1,true,false,"conv4b_concat_data","conv4b_reduce_data","conv4b_reduce",model,data, 0,hd);
	inferx_batchnorm(0.999,1e-3,true,"conv4b_reduce_data","conv4b_reduce_data","conv4b_reduce_bn",model,data,hd);
	inferx_scale(1,1,true,"conv4b_reduce_data","conv4b_reduce_data","conv4b_reduce_scale",model,data,hd);
	inferx_relu("conv4b_reduce_data","conv4b_reduce_data","conv4b_reduce_relu",model,data,hd);
	bottom_vector[0] = "conv4a_data";	bottom_vector[1] = "conv4b_reduce_data";
	coeffs[0]=1.000000; coeffs[1]=1.000000; 
	inferx_eltwise(2,coeffs,SUM,true,2,bottom_vector,"conv4b_data","conv4b",model,data,hd);
	inferx_convolution(128,24,3,3,1,1,1,1,1,1,1,true,false,"conv3b_data","conv3b_mbox_loc_data","conv3b_mbox_loc",model,data, 0,hd);
	inferx_convolution(128,12,3,3,1,1,1,1,1,1,1,true,false,"conv3b_data","conv3b_mbox_conf_data","conv3b_mbox_conf",model,data, 0,hd);
	inferx_convolution(256,24,3,3,1,1,1,1,1,1,1,true,false,"conv4b_data","conv4b_mbox_loc_data","conv4b_mbox_loc",model,data, 0,hd);
	inferx_convolution(256,12,3,3,1,1,1,1,1,1,1,true,false,"conv4b_data","conv4b_mbox_conf_data","conv4b_mbox_conf",model,data, 0,hd);

	inferx_sort_data("conv4b_mbox_conf_data",data, hd);
	//inferx_print_data("conv4b_mbox_conf_data",data, hd);
	if(pout)
	  *pout = inferx_get_data("conv4b_mbox_conf_data",data,hd);
	inferx_finalize("ShipSSD",hd);

	return;
}