/*
	This file is generated by net_compiler.py.
	The use of included functions list as follows:

	Input:
	Input(int dim1,int dim2,int dim3,int dim4,char *top,char *name)

	inferx_convolution:
	inferx_convolution(int num_input,int num_output,int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,int group,int dilation,int axis,bool bias_term,bool force_nd_im2col,char *bottom,char *top, char *name)

	inferx_batchnorm:
	inferx_batchnorm(float moving_average_fraction,float eps,bool use_global_stats,char *bottom,char *top,char *name)

	inferx_scale:
	inferx_scale(int axis,int num_axes,bool bias_term,char *bottom,char *top,char *name)

	inferx_relu:
	inferx_relu(char *bottom,char *top,char *name)

	inferx_pooling:
	inferx_pooling(int kernel_h,int kernel_w,int stride_h,int stride_w,int pad_h,int pad_w,enum PoolMethod pool,char *bottom,char *top,char *name)
*/

#include "inferxlite_common.h"
#include "interface.h"
void YOLOtiny(char * path, char * model, char * data, void * pdata, void **pout, struct handler *hd)
{
	static long nchw[4];
        inferx_net_preprocess(data, model, nchw, hd);

        printf("=== enter YOLOtiny ===\n");

	inferx_input(nchw,pdata,"data_data","data",model,data,hd);
	inferx_convolution(3,16,3,3,1,1,1,1,1,1,1,false,false,"data_data","layer1-conv_data","layer1-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer1-conv_data","layer1-conv_data","layer1-bn",model,data,hd);
	inferx_scale(1,1,true,"layer1-conv_data","layer1-conv_data","layer1-scale",model,data,hd);
	inferx_relu("layer1-conv_data","layer1-conv_data","layer1-act",model,data,hd);

	inferx_pooling(2,2,2,2,0,0,MAX,"layer1-conv_data","layer2-maxpool_data","layer2-maxpool",model,data,hd);

	inferx_convolution(16,32,3,3,1,1,1,1,1,1,1,false,false,"layer2-maxpool_data","layer3-conv_data","layer3-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer3-conv_data","layer3-conv_data","layer3-bn",model,data,hd);
	inferx_scale(1,1,true,"layer3-conv_data","layer3-conv_data","layer3-scale",model,data,hd);
	inferx_relu("layer3-conv_data","layer3-conv_data","layer3-act",model,data,hd);


	inferx_pooling(2,2,2,2,0,0,MAX,"layer3-conv_data","layer4-maxpool_data","layer4-maxpool",model,data,hd);

	inferx_convolution(32,64,3,3,1,1,1,1,1,1,1,false,false,"layer4-maxpool_data","layer5-conv_data","layer5-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer5-conv_data","layer5-conv_data","layer5-bn",model,data,hd);
	inferx_scale(1,1,true,"layer5-conv_data","layer5-conv_data","layer5-scale",model,data,hd);
	inferx_relu("layer5-conv_data","layer5-conv_data","layer5-act",model,data,hd);

	inferx_pooling(2,2,2,2,0,0,MAX,"layer5-conv_data","layer6-maxpool_data","layer6-maxpool",model,data,hd);

	inferx_convolution(64,128,3,3,1,1,1,1,1,1,1,false,false,"layer6-maxpool_data","layer7-conv_data","layer7-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer7-conv_data","layer7-conv_data","layer7-bn",model,data,hd);
	inferx_scale(1,1,true,"layer7-conv_data","layer7-conv_data","layer7-scale",model,data,hd);
	inferx_relu("layer7-conv_data","layer7-conv_data","layer7-act",model,data,hd);

	inferx_pooling(2,2,2,2,0,0,MAX,"layer7-conv_data","layer8-maxpool_data","layer8-maxpool",model,data,hd);

	inferx_convolution(128,256,3,3,1,1,1,1,1,1,1,false,false,"layer8-maxpool_data","layer9-conv_data","layer9-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer9-conv_data","layer9-conv_data","layer9-bn",model,data,hd);
	inferx_scale(1,1,true,"layer9-conv_data","layer9-conv_data","layer9-scale",model,data,hd);
	inferx_relu("layer9-conv_data","layer9-conv_data","layer9-act",model,data,hd);


	inferx_pooling(2,2,2,2,0,0,MAX,"layer9-conv_data","layer10-maxpool_data","layer10-maxpool",model,data,hd);

	inferx_convolution(256,512,3,3,1,1,1,1,1,1,1,false,false,"layer10-maxpool_data","layer11-conv_data","layer11-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer11-conv_data","layer11-conv_data","layer11-bn",model,data,hd);
	inferx_scale(1,1,true,"layer11-conv_data","layer11-conv_data","layer11-scale",model,data,hd);
	inferx_relu("layer11-conv_data","layer11-conv_data","layer11-act",model,data,hd);


	inferx_pooling_yolo(2,2,1,1,1,1,MAX,"layer11-conv_data","layer12-maxpool_data","layer12-maxpool",model,data,hd);


	inferx_convolution(512,1024,3,3,1,1,1,1,1,1,1,false,false,"layer12-maxpool_data","layer13-conv_data","layer13-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer13-conv_data","layer13-conv_data","layer13-bn",model,data,hd);
	inferx_scale(1,1,true,"layer13-conv_data","layer13-conv_data","layer13-scale",model,data,hd);
	inferx_relu("layer13-conv_data","layer13-conv_data","layer13-act",model,data,hd);

	inferx_convolution(1024,1024,3,3,1,1,1,1,1,1,1,false,false,"layer13-conv_data","layer14-conv_data","layer14-conv",model,data,0,hd);
	inferx_batchnorm(0.999,1e-9,true,"layer14-conv_data","layer14-conv_data","layer14-bn",model,data,hd);
	inferx_scale(1,1,true,"layer14-conv_data","layer14-conv_data","layer14-scale",model,data,hd);
	inferx_relu("layer14-conv_data","layer14-conv_data","layer14-act",model,data,hd);


	inferx_convolution(1024,75,1,1,1,1,0,0,1,1,1,true,false,"layer14-conv_data","layer15-conv_data","layer15-conv",model,data,0,hd);

        if(pout)
          *pout = inferx_get_data("layer15-conv_data",data,hd);

	inferx_finalize("YOLOtiny",hd);

	return;
}
